#!/bin/zsh
if test ! -e /root/.alias; then
	cp /usr/share/absps/config/.alias /root/
fi
if test ! -e /root/.zshrc; then
	cp /usr/share/absps/config/.zshrc /root/
fi
if test ! -e /root/.screenrc; then
	cp /usr/share/absps/config/.screenrc /root/
fi
if test ! -e /root/.config; then
	cp -r /usr/share/absps/config/.config /root/
fi
if test ! -e /root/.gitignore; then
	cp -r /usr/share/absps/config/.gitignore /root/
fi

