#!/bin/sh
git clone https://github.com/tpope/vim-pathogen.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/vim-airline/vim-airline.git
git clone https://github.com/vim-airline/vim-airline-themes.git
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/easymotion/vim-easymotion.git
git clone https://github.com/vim-latex/vim-latex.git
